import JSZip from "jszip";
import * as THREE from "three";

// Build a synthetic .3mf that looks like a Bambu / Prusa export — i.e. it
// contains realistic vendor-private metadata that the sanitizer should strip.
// Used by the "Try a sample" button so visitors can demo the tool without
// hunting down a real Bambu .3mf file first.

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml" />
  <Default Extension="png" ContentType="image/png" />
</Types>`;

const RELS = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>`;

// Fake project settings that pretend to be Bambu Studio cache.
const BAMBU_PROJECT_SETTINGS = `{
  "different_settings_to_system": [],
  "filament_settings_id": ["Generic PLA @BBL X1C"],
  "printer_settings_id": "Bambu Lab X1 Carbon 0.4 nozzle",
  "print_settings_id": "0.20mm Standard @BBL X1C",
  "ams_mapping": [0, 1, 2, 3],
  "presets_url": "https://makerworld.com/...",
  "version": "01.09.05.51"
}`;

const BAMBU_SLICE_INFO = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header>
    <header_item key="X-BBL-Client-Type" value="slicer"/>
    <header_item key="X-BBL-Client-Version" value="01.09.05.51"/>
  </header>
  <plate>
    <metadata key="objects_info" value="..."/>
    <filament id="1" tray_info_idx="GFA00" type="PLA"/>
  </plate>
</config>`;

const PRUSA_PROJECT_SETTINGS = `; generated by PrusaSlicer 2.7.4+win64 on 2026-05-13
filament_type = PLA
filament_settings_id = "Prusament PLA"
print_settings_id = "0.20mm SPEED @MK4S"
printer_settings_id = "Original Prusa MK4S 0.4 nozzle"
nozzle_diameter = 0.4
pressure_advance = 0.045`;

function buildModelXml(
  vendor: "bambu" | "prusa",
  positions: Float32Array,
  indices: Uint32Array,
): string {
  const lines: string[] = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);

  if (vendor === "bambu") {
    lines.push(
      `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:BambuStudio="http://schemas.bambulab.com/package/2021" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06">`,
    );
    lines.push(`  <metadata name="Application">BambuStudio-01.09.05.51</metadata>`);
    lines.push(`  <metadata name="BambuStudio:3mfVersion">1</metadata>`);
    lines.push(`  <BambuStudio:filament_map>1,2,3,4</BambuStudio:filament_map>`);
  } else {
    lines.push(
      `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">`,
    );
    lines.push(`  <metadata name="Application">PrusaSlicer-2.7.4</metadata>`);
    lines.push(`  <slic3rpe:source>PrusaSlicer</slic3rpe:source>`);
  }

  lines.push(`  <resources>`);
  lines.push(`    <object id="1" type="model">`);
  lines.push(`      <mesh>`);
  lines.push(`        <vertices>`);
  for (let i = 0; i < positions.length; i += 3) {
    lines.push(
      `          <vertex x="${positions[i].toFixed(4)}" y="${positions[i + 1].toFixed(4)}" z="${positions[i + 2].toFixed(4)}" />`,
    );
  }
  lines.push(`        </vertices>`);
  lines.push(`        <triangles>`);
  for (let i = 0; i < indices.length; i += 3) {
    lines.push(
      `          <triangle v1="${indices[i]}" v2="${indices[i + 1]}" v3="${indices[i + 2]}" />`,
    );
  }
  lines.push(`        </triangles>`);
  lines.push(`      </mesh>`);
  lines.push(`    </object>`);
  lines.push(`  </resources>`);
  lines.push(`  <build>`);
  if (vendor === "bambu") {
    lines.push(`    <item objectid="1" p:UUID="00000000-0000-0000-0000-000000000001" />`);
  } else {
    lines.push(`    <item objectid="1" />`);
  }
  lines.push(`  </build>`);
  lines.push(`</model>`);

  return lines.join("\n");
}

function indexFromPositions(positionCount: number): Uint32Array {
  const idx = new Uint32Array(positionCount);
  for (let i = 0; i < positionCount; i++) idx[i] = i;
  return idx;
}

function torusKnotGeometryData(): { positions: Float32Array; indices: Uint32Array } {
  const geo = new THREE.TorusKnotGeometry(10, 3, 64, 8);
  const pos = geo.attributes.position;
  const positions = new Float32Array(pos.array);
  let indices: Uint32Array;
  const indexAttr = geo.getIndex();
  if (indexAttr) {
    indices = new Uint32Array(indexAttr.array);
  } else {
    indices = indexFromPositions(positions.length / 3);
  }
  geo.dispose();
  return { positions, indices };
}

export async function buildSampleBambu3MF(): Promise<File> {
  const { positions, indices } = torusKnotGeometryData();
  const zip = new JSZip();
  zip.file("[Content_Types].xml", CONTENT_TYPES);
  zip.folder("_rels")!.file(".rels", RELS);
  zip.folder("3D")!.file("3dmodel.model", buildModelXml("bambu", positions, indices));
  // Bambu-private files that should be stripped:
  const meta = zip.folder("Metadata")!;
  meta.file("project_settings.config", BAMBU_PROJECT_SETTINGS);
  meta.file("slice_info.config", BAMBU_SLICE_INFO);
  meta.file("plate_1.config", "# fake bambu plate config\n");
  zip.folder("Auxiliaries")!.file("readme.txt", "Demo Bambu Studio export bundle");
  const blob = await zip.generateAsync({
    type: "blob",
    mimeType: "model/3mf",
    compression: "DEFLATE",
  });
  return new File([blob], "flip3d-sample-bambu.3mf", { type: "model/3mf" });
}

export async function buildSamplePrusa3MF(): Promise<File> {
  const { positions, indices } = torusKnotGeometryData();
  const zip = new JSZip();
  zip.file("[Content_Types].xml", CONTENT_TYPES);
  zip.folder("_rels")!.file(".rels", RELS);
  zip.folder("3D")!.file("3dmodel.model", buildModelXml("prusa", positions, indices));
  const meta = zip.folder("Metadata")!;
  meta.file("Slic3r_PE.config", PRUSA_PROJECT_SETTINGS);
  meta.file("Slic3r_PE_model.config", "<?xml version=\"1.0\"?><config><object id=\"1\" instances_count=\"1\"/></config>");
  const blob = await zip.generateAsync({
    type: "blob",
    mimeType: "model/3mf",
    compression: "DEFLATE",
  });
  return new File([blob], "flip3d-sample-prusa.3mf", { type: "model/3mf" });
}
